---
# defaults file for install-microk8s
## specific microk8s version
microk8s_version: 1.22/stable

## Cache update time for apt module
microk8s_cache_valid_time: 3600

## plugin configuration
microk8s_plugins:
  #   dashboard: false        # The Kubernetes dashboard
  dns: true # CoreDNS
#   helm3: false            # Helm 3 - Kubernetes package manager
#   host-access: false      # Allow Pods connecting to Host services smoothly
#   ingress: false          # Ingress controller for external access
#   metrics-server: false   # K8s Metrics Server for API access to service
#                           # metrics
#   rbac: false             # Role-Based Access Control for authorisation
#   registry: false         # Private image registry exposed on localhost:32000
#   storage: false          # Storage class; allocates storage from host
#                           # directory
#   ambassador: false       # Ambassador API Gateway and Ingress
#   cilium: false           # SDN, fast with full network policy
#   fluentd: false          # Elasticsearch-Fluentd-Kibana logging and
#                           # monitoring
#   gpu: false              # Automatic enablement of Nvidia CUDA
#   helm: false             # Helm 2 - the package manager for Kubernetes
#   istio: false            # Core Istio service mesh services
#   jaeger: false           # Kubernetes Jaeger operator with its simple config
#   knative: false          # The Knative framework on Kubernetes.
#   kubeflow: false         # Kubeflow for easy ML deployments
#   linkerd: false          # Linkerd is a service mesh for Kubernetes
#   #                         and other frameworks
#   metallb: false          # Loadbalancer for your Kubernetes cluster
#   multus: false           # Multus CNI enables attaching multiple network
#   #                         interfaces to pods
#   prometheus: false       # Prometheus operator for monitoring and logging
#   traefik: false

microk8s_dns_servers:
  - 10.88.1.86

## microk8s_users to make members of microk8s group
microk8s_users:
  - osadmin
