---
# tasks file for install-microk8s
- name: install microk8s
  ansible.builtin.import_tasks:
    file: install.yml
  tags:
    - always
    - microk8s

- name: configure microk8s Users
  ansible.builtin.include_tasks:
    file: configure-groups.yml
  when:
    - microk8s_users is defined
    - microk8s_users not in ([], None, '', omit)
  tags:
    - microk8s
    - microk8s.users
